# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ShPwi4k3dQiR-Ij-gvy9GlVw39xLH3vo
"""

print("hello")

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report,confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

#load dataset
df = pd.read_csv(r"/content/heart.csv")

df.head()

df['target'].value_counts()

df.info()

corr = df.corr()

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(14, 12))

sns.heatmap(corr, annot=True, fmt=".2f", cmap="coolwarm",
            linewidth=0.5, cbar_kws={"shrink": 0.75})

plt.xticks(rotation=45, ha='right')
plt.yticks(rotation=0)
plt.title("Correlation Matrix Heatmap", fontsize=16)
plt.show()

print(df.isnull().sum())

features =['age','sex',	'cp','trestbps','chol'	,'fbs',	'restecg'	,'thalach','exang',	'oldpeak',	'slope',	'ca',	'thal']
X = df.drop('target', axis=1)
y = df['target']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = DecisionTreeClassifier(random_state=42)
model.fit(X_train,y_train)

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy:.2f}')

print('\nClassification Report:')
print(classification_report(y_test, y_pred))

print('\nConfusion Matrix:')
print(confusion_matrix(y_test, y_pred))

conf_matrix = confusion_matrix(y_test,y_pred)
sns.heatmap(conf_matrix, annot =True, fmt ='d', cmap='Blues')
plt.xlabel('predicted')
plt.ylabel('Actual')
plt.title('confusion matrix')
plt.show()

plt.figure(figsize=(20, 10))
plot_tree(model,
          filled=True,
          feature_names=X.columns,
          class_names=['No Disease', 'Disease'],
          rounded=True,
          fontsize=10)
plt.show()